import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { 
    PlayerGeneratedModule,
    AdministratorGeneratedModule,
    PublisherGeneratedModule, 
    PublisherGeneratedSharedModule 
} from './generated/module.js';
import { PublisherValidator, registerValidationChecks } from './publisher-validator.js';
import { AdministratorValidator } from './administrator-validator.js';
import { PlayerValidator } from './player-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SharedAddedServices = {
    validation: {
        PublisherValidator: PublisherValidator,
        AdministratorValidator: AdministratorValidator,
        PlayerValidator: PlayerValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SharedServices = LangiumServices & SharedAddedServices



/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PublisherModule: Module<SharedServices, PartialLangiumServices & SharedAddedServices> = {
    validation: {
        PublisherValidator: () => new PublisherValidator(),
        AdministratorValidator: () => new AdministratorValidator(),
        PlayerValidator: () => new PlayerValidator()
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSharedServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Publisher: SharedServices,
    Administrator: SharedServices,
    Player: SharedServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PublisherGeneratedSharedModule
    );
    const Publisher = inject(
        createDefaultModule({ shared }),
        PublisherGeneratedModule,
        PublisherModule
    );
    const Administrator = inject(
        createDefaultModule({ shared }),
        AdministratorGeneratedModule,
        PublisherModule
    );
    const Player = inject(
        createDefaultModule({ shared }),
        PlayerGeneratedModule,
        PublisherModule
    );
    shared.ServiceRegistry.register(Publisher);
    shared.ServiceRegistry.register(Administrator);
    shared.ServiceRegistry.register(Player);
    registerValidationChecks(Publisher);
    registerValidationChecks(Administrator);
    registerValidationChecks(Player);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Publisher, Player, Administrator };
}
