import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import {
    PlayerGeneratedModule,
    AdministratorGeneratedModule,
    PublisherGeneratedModule,
    PublisherGeneratedSharedModule
} from './generated/module.js';
import { PublisherValidator, registerValidationChecksPublisher } from './publisher-validator.js';
import { AdministratorValidator, registerValidationChecksAdministrator } from './administrator-validator.js';
import { PlayerValidator, registerValidationChecksPlayer } from './player-validator.js';
import { databaseModel } from './db-model.js';
import { DatabaseService } from './db-service.js';
import { SharedScopeProvider } from './shared-scope-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SharedAddedServices = {
    validation: {
        PublisherValidator: PublisherValidator,
        AdministratorValidator: AdministratorValidator,
        PlayerValidator: PlayerValidator
    },
    db: {
        DatabaseService: DatabaseService
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SharedServices = LangiumServices & SharedAddedServices



/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SharedModule: Module<SharedServices, PartialLangiumServices & SharedAddedServices> = {
    validation: {
        PublisherValidator: () => new PublisherValidator(),
        AdministratorValidator: () => new AdministratorValidator(),
        PlayerValidator: (services) => new PlayerValidator(services)
    },
    db: {
        DatabaseService: () => new DatabaseService()
    },
    references: {
        ScopeProvider: (services: LangiumServices) => new SharedScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSharedServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Publisher: SharedServices,
    Administrator: SharedServices,
    Player: SharedServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PublisherGeneratedSharedModule
    );
    const Publisher = inject(
        createDefaultModule({ shared }),
        PublisherGeneratedModule,
        SharedModule
    );
    const Administrator = inject(
        createDefaultModule({ shared }),
        AdministratorGeneratedModule,
        SharedModule
    );
    const Player = inject(
        createDefaultModule({ shared }),
        PlayerGeneratedModule,
        SharedModule
    );
    shared.ServiceRegistry.register(Publisher);
    shared.ServiceRegistry.register(Administrator);
    shared.ServiceRegistry.register(Player);
    registerValidationChecksPublisher(Publisher);
    registerValidationChecksAdministrator(Administrator);
    registerValidationChecksPlayer(Player);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Publisher, Player, Administrator };
}
